name: Build Flashable Kernel for OnePlus 3

on:
  push:
    branches: [ eleven ]
  workflow_dispatch:

jobs:
  kernel-build:
    name: Compile & Pack Kernel
    runs-on: ubuntu-latest

    env:
      KERNEL_NAME: Image.gz-dtb
      DEFCONFIG: lineage_oneplus3_defconfig
      ARCH: arm64
      SUBARCH: arm64
      CLANG_PATH: ${{ github.workspace }}/clang

    steps:
      - name: 🧹 Clean up runner
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
          df -h

      - name: 📥 Checkout kernel source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 🧰 Clone Clang toolchain
        run: |
          git clone --depth=1 https://github.com/KudProject/prebuilt_clang clang

      - name: 📂 Create output directory
        run: mkdir out

      - name: ⚙️ Kernel defconfig
        run: |
          export PATH="$CLANG_PATH/bin:$PATH"
          make O=out ARCH=$ARCH SUBARCH=$SUBARCH \
               CC=clang CROSS_COMPILE=aarch64-linux-android- \
               CLANG_TRIPLE=aarch64-linux-gnu- \
               $DEFCONFIG

      - name: 🚀 Build kernel
        run: |
          export PATH="$CLANG_PATH/bin:$PATH"
          make -j$(nproc) O=out ARCH=$ARCH SUBARCH=$SUBARCH \
               CC=clang CROSS_COMPILE=aarch64-linux-android- \
               CLANG_TRIPLE=aarch64-linux-gnu-

      - name: 🧾 Verify built image
        run: |
          file out/arch/arm64/boot/$KERNEL_NAME
          ls -lh out/arch/arm64/boot/

      - name: 📦 Clone AnyKernel3
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3 anykernel
          cp out/arch/arm64/boot/$KERNEL_NAME anykernel/

      - name: 📦 Create flashable zip
        run: |
          cd anykernel
          zip -r9 Flashable-Kernel-OnePlus3.zip * -x .git README.md

      - name: ⬆️ Upload flashable zip
        uses: actions/upload-artifact@v4
        with:
          name: Flashable-Kernel-OnePlus3
          path: anykernel/Flashable-Kernel-OnePlus3.zip
